### ISSUE TITLE
Error with regards to math_functions.php

### ISSUE THREAD

**Issue by steentje34** [lsgs/redcap-drw-tweaks#1]
Hi @lsgs,

We received an error when using this External Module:

> The 'hook_every_page_before_render' hook did not complete for the 'drw_tweaks' module because of the following error. Stack traces are unfortunately not available for this type of error:
> 
> Error Message: require_once(): Failed opening required '/var/www/html/studies/redcap_v10.0.20/ProjectGeneral/math_functions.php' (include_path='.:/var/www/html/studies/redcap_v10.0.20/Libraries/PEAR/:.:/usr/share/pear:/usr/share/php')
> File: /var/www/html/studies/modules/drw_tweaks_v1.0.0/DataQualityTweaked.php
> Line: 6
> 
> 
> URL: https://studiesredcap.uzgent.be/redcap_v10.0.20/DataQuality/resolve_csv_export.php?pid=137&status_type=OPEN_UNRESPONDED&field_rule_filter=&group_id=189

Indeed, the file .../ProjectGeneral/math_functions.php is not available in REDCap v10.0.20. Could this be fixed please?

Thanks in advance!
Kind regards,
Simon (University Hospital Ghent)

**Comment by lsgs** [comment]
Look out for release 1.0.1 @steentje34. The CSV export functionality implemented by this module is no longer needed as it got implemented as standard functionality in the REDCap core code. I've included a version check on the behavior so it is automatically disabled for versions where it's not needed. The "verify all" still functions as before. I had also looked at whether I could implement a "reassign user" tweak but now that is not required either! :)
